<a href="https://colab.research.google.com/github/vivandsouza/TSAI/blob/master/Back_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## Weights
w1 = 0.15
w2 = 0.20
w3 = 0.10
w4 = 0.12
w5 = 0.11
w6 = 0.16

## Inputs
i1 = 2
i2 = 3

## Output
actual = 1


## Forward pass
h1_h2 = np.matmul(np.array([[i1, i2]]), np.array([[w1, w3], [w2, w4]]))
print(h1_h2)
prediction = np.matmul(h1_h2, np.array([[w5], [w6]]))
print(prediction)

## Calculating the error
Error = ((prediction - actual)**2)/2
print(Error)


## Back propagation
delta = prediction - actual
a = 0.05   ## Learning rate

##new w5 and w6 weights
w5_w6_new = np.array([[w5], [w6]]) - ((a*delta) * np.array(h1_h2.T))
print(w5_w6_new)

## new w1, w2, w3 and w4 weights
w1_w2_w3_w4_new = np.array([[w1, w3], [w2, w4]]) - ((a*delta) * (np.matmul(np.array([[i1], [i2]]), np.array([[w5, w6]]))))
print(w1_w2_w3_w4_new)


h1_h2_new =np.matmul(np.array([[i1, i2]]), w1_w2_w3_w4_new)
print(h1_h2_new)

final_layer_new = np.matmul(h1_h2_new, w5_w6_new)
print(final_layer_new)




[[0.9  0.56]]
[[0.1886]]
[[0.32918498]]
[[0.146513 ]
 [0.1827192]]
[[0.1589254 0.1129824]
 [0.2133881 0.1394736]]
[[0.9580151 0.6443856]]
[[0.25810329]]


In [0]:
import numpy as np

## Weights
w1 = 0.16
w2 = 0.21
w3 = 0.11
w4 = 0.14
w5 = 0.15
w6 = 0.18

## Inputs
i1 = 2
i2 = 3

## Output
actual = 1

## Forward pass
h1_h2 = np.matmul(np.array([[i1, i2]]), np.array([[w1, w3], [w2, w4]]))
print(h1_h2)
prediction = np.matmul(h1_h2, np.array([[w5], [w6]]))
print(prediction)

## Calculating the error
Error = ((prediction - actual)**2)/2
print(Error)


## Back propagation
delta = prediction - actual
a = 0.05   ## Learning rate

##new w5 and w6 weights
w5_w6_new = np.array([[w5], [w6]]) - ((a*delta) * np.array(h1_h2.T))
print(w5_w6_new)

## new w1, w2, w3 and w4 weights
w1_w2_w3_w4_new = np.array([[w1, w3], [w2, w4]]) - ((a*delta) * (np.matmul(np.array([[i1], [i2]]), np.array([[w5, w6]]))))
print(w1_w2_w3_w4_new)


h1_h2_new =np.matmul(np.array([[i1, i2]]), w1_w2_w3_w4_new)
print(h1_h2_new)

final_layer_new = np.matmul(h1_h2_new, w5_w6_new)
print(final_layer_new)



[[0.95 0.64]]
[[0.2577]]
[[0.27550464]]
[[0.18525925]
 [0.2037536 ]]
[[0.1711345  0.1233614 ]
 [0.22670175 0.1600421 ]]
[[1.02237425 0.7268491 ]]
[[0.33750241]]
